"""empty message

Revision ID: 07eada801fbc
Revises: 1d2d90100cb5
Create Date: 2022-07-08 23:04:45.120910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eada801fbc'
down_revision = '1d2d90100cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'people', ['id'])
    op.add_column('user', sa.Column('_password', sa.String(length=255), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', '_password')
    op.drop_constraint(None, 'people', type_='unique')
    # ### end Alembic commands ###
